# Common makefile for software
#
# Copyright (c) 2020-2022 Ross Bamford and contributors
# See LICENSE

ifndef MEGA_MICROS_DIR
$(error MEGA_MICROS_DIR is not set)
endif

-include $(MEGA_MICROS_DIR)/user.mk

CPU?=68030
ARCH?=$(CPU)
TUNE?=$(CPU)

REMOTE_USER=bob@192.168.1.76
REMOTE_DIR=OneDrive/1_Srec

# We can build for bare metal or for bios
BAREMETAL?=false

ifeq ($(BAREMETAL),true)
SYSINCDIR?=$(MEGA_MICROS_DIR)/built/include
SYSLIBDIR?=$(MEGA_MICROS_DIR)/built/lib/bare

LDSCRIPT?=$(MEGA_MICROS_DIR)/built/lib/bare/program.ld
ROM_LDSCRIPT?=$(MEGA_MICROS_DIR)/built/lib/bare/rom_program.ld

DEFINES=-DBAREMETAL
else
SYSINCDIR?=$(MEGA_MICROS_DIR)/built/include
SYSLIBDIR?=$(MEGA_MICROS_DIR)/built/lib/bios

LDSCRIPT?=$(MEGA_MICROS_DIR)/built/lib/bios/program.ld
ROM_LDSCRIPT?=none

DEFINES=-DUSEBIOS
endif

FLAGS=-ffreestanding -ffunction-sections -fdata-sections -fomit-frame-pointer	\
      -Wall -Wextra -Werror -Wno-unused-function -pedantic -I$(SYSINCDIR)			\
      -mcpu=$(CPU) -march=$(ARCH) -mtune=$(TUNE) -msoft-float -g -O2 $(DEFINES)
CFLAGS=-std=c11 $(FLAGS)
CXXFLAGS=-std=c++20 -fno-exceptions -fno-rtti $(FLAGS)
GCC_LIBS?=$(shell $(CC) --print-search-dirs \
          | grep libraries:\ = \
          | sed 's/libraries: =/-L/g' \
          | sed 's/:/\/ -L/g')
LIBS=$(EXTRA_LIBS) -lmega -lgcc
ASFLAGS=-mcpu=$(CPU) -march=$(ARCH)
VASMFLAGS=-Felf -m$(CPU) -quiet -Lnf $(DEFINES)
COMMON_LDFLAGS=-L$(SYSLIBDIR) -Map=$(MAP) -z noexecstack --gc-sections --oformat=elf32-m68k $(EXTRA_LDFLAGS)
LDFLAGS=$(COMMON_LDFLAGS) -T$(LDSCRIPT) 
ROM_LDFLAGS=$(COMMON_LDFLAGS) -T$(ROM_LDSCRIPT) 

GCC_68K_PFX=m68k-linux-gnu
CC=$(GCC_68K_PFX)-gcc
CXX=$(GCC_68K_PFX)-g++
AS=$(GCC_68K_PFX)-as
LD=$(GCC_68K_PFX)-ld
NM=$(GCC_68K_PFX)-nm
OBJDUMP=$(GCC_68K_PFX)-objdump
OBJCOPY=$(GCC_68K_PFX)-objcopy
SIZE=$(GCC_68K_PFX)-size
VASM=vasmm68k_mot
RM=rm -f
CP=cp
LSOF=lsof

# GCC-version-specific settings
ifneq ($(findstring GCC,$(shell $(CC) --version 2>/dev/null)),)
CC_VERSION:=$(shell $(CC) -dumpfullversion)
CC_MAJOR:=$(firstword $(subst ., ,$(CC_VERSION)))
# If this is GCC 12, 13, or 14, add flag --param=min-pagesize=0 to CFLAGS
ifeq ($(CC_MAJOR),12)
CFLAGS+=--param=min-pagesize=0
endif
ifeq ($(CC_MAJOR),13)
CFLAGS+=--param=min-pagesize=0
endif
ifeq ($(CC_MAJOR),14)
CFLAGS+=--param=min-pagesize=0
endif
endif

# For systems without MMU support, aligning LOAD segments with pages is not needed
# In those cases, provide fake page sizes to both save space and remove RWX warnings
ifeq ($(CPU),68030)
LD_SUPPORT_MMU?=true
endif
ifeq ($(CPU),68040)
LD_SUPPORT_MMU?=true
endif
ifeq ($(CPU),68060)
LD_SUPPORT_MMU?=true
endif
LD_SUPPORT_MMU?=false
ifneq ($(LD_SUPPORT_MMU),true)
# Saves space in binaries, but will break MMU use
LDFLAGS+=-z max-page-size=16 -z common-page-size=16
endif

# Output config (assume name of directory)
PROGRAM_BASENAME=$(shell basename $(CURDIR))

# Set other output files using output basname
ELF=$(PROGRAM_BASENAME).elf
ROM_ELF=$(PROGRAM_BASENAME)_rom.elf
BINARY=$(PROGRAM_BASENAME).bin
SREC=$(PROGRAM_BASENAME).srec
ROM_SREC=$(PROGRAM_BASENAME)_rom.srec
DISASM=$(PROGRAM_BASENAME).dis
ROM_DISASM=$(PROGRAM_BASENAME)_rom.dis
MAP=$(PROGRAM_BASENAME).map
SYM=$(PROGRAM_BASENAME).sym
ROM_SYM=$(PROGRAM_BASENAME)_rom.sym

# Assume source files in Makefile directory are source files for project
CSOURCES=$(wildcard *.c)
CXXSOURCES=$(wildcard *.cpp)
CINCLUDES=$(wildcard *.h)
SSOURCES=$(wildcard *.S)
ASMSOURCES=$(wildcard *.asm)
SOURCES=$(CSOURCES) $(CXXSOURCES) $(SSOURCES) $(ASMSOURCES)

# Assume each source files makes an object file
OBJECTS=$(addsuffix .o,$(basename $(SOURCES)))

TO_CLEAN=$(OBJECTS) $(ELF) $(BINARY) $(SREC) $(MAP) $(SYM) $(DISASM) $(addsuffix .lst,$(basename $(SSOURCES) $(ASMSOURCES)))

all: $(BINARY) $(SREC) $(DISASM)

rom: $(ROM_ELF) $(ROM_SREC) $(ROM_DISASM)

$(ELF) : $(OBJECTS) $(ROM_OBJ)
	$(LD) $(LDFLAGS) $(GCC_LIBS) $^ $(LIBS) -o $(ELF)
	$(NM) --numeric-sort $(ELF) >$(SYM)
	$(SIZE) $(ELF)
	-chmod a-x $(ELF)

$(ROM_ELF) : $(OBJECTS) $(ROM_OBJ)
	$(LD) $(ROM_LDFLAGS) $(GCC_LIBS) $^ $(LIBS) -o $(ROM_ELF)
	$(NM) --numeric-sort $(ROM_ELF) >$(ROM_SYM)
	$(SIZE) $(ROM_ELF)
	-chmod a-x $(ROM_ELF)

$(BINARY) : $(ELF)
	$(OBJCOPY) -O binary $(ELF) $(BINARY)

$(SREC) : $(ELF)
	$(OBJCOPY) -O srec $(ELF) $(SREC)

$(ROM_SREC) : $(ROM_ELF)
	$(OBJCOPY) -O srec $(ROM_ELF) $(ROM_SREC)

$(DISASM) : $(ELF)
	$(OBJDUMP) --disassemble -S $(ELF) >$(DISASM)

$(ROM_DISASM) : $(ROM_ELF)
	$(OBJDUMP) --disassemble -S $(ROM_ELF) >$(ROM_DISASM)

$(OBJECTS): Makefile

%.o : %.c $(CINCLUDES)
	$(CC) -c $(CFLAGS) $(EXTRA_CFLAGS) -o $@ $<

%.o : %.cpp
	$(CXX) -c $(CXXFLAGS) $(EXTRA_CXXFLAGS) -o $@ $<

%.o : %.S
	$(AS) $(ASFLAGS) -o $@ $<

%.o : %.asm
	$(VASM) $(VASMFLAGS) $(EXTRA_VASMFLAGS) -L $(basename $@).lst -o $@ $<

# remove targets that can be generated by this Makefile
clean:
	$(RM) $(TO_CLEAN)

disasm: $(DISASM)

# hexdump of program binary
dump: $(BINARY)
	hexdump -C $(BINARY)

install: all
	scp $(SREC) $(REMOTE_USER):$(REMOTE_DIR)

zob:
	echo BAREMETAL is $(BAREMETAL)

# Makefile magic (for "phony" targets that are not real files)
.PHONY: all rom clean disasm dump install zob
